// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookingSystem.Shared.Data;

#nullable disable

namespace OnlineBookingSystem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409115007_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.AdvertisementEntity", b =>
                {
                    b.Property<int>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdID"));

                    b.Property<string>("AdImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("AdID");

                    b.ToTable("Advertisement", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BankAccountDetailEntity", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChequeInFavour")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BankId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("BankAccountDetail", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingCategoryEntity", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DocumentLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentityFormat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("BookingCategory", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingPurposeEntity", b =>
                {
                    b.Property<int>("PurposeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurposeID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<string>("PurposeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PurposeID");

                    b.ToTable("BookingPurpose", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingRequestEntity", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("BookingFromDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingRegNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("BookingToDate")
                        .HasColumnType("date");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Level1UserID")
                        .HasColumnType("int");

                    b.Property<int?>("Level2UserID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PurposeID")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SecurityDeposit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("\"RentAmount\" + \"SecurityDeposit\"", true);

                    b.Property<int>("TotalDays")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST((julianday(\"BookingToDate\") - julianday(\"BookingFromDate\")) AS INTEGER) + 1", true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("BookingRegNo")
                        .IsUnique();

                    b.HasIndex("CategoryID");

                    b.HasIndex("PurposeID");

                    b.HasIndex("UserID");

                    b.HasIndex("VenueID");

                    b.ToTable("BookingRequest", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingStatusLogEntity", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByID")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LogID");

                    b.HasIndex("BookingID");

                    b.ToTable("BookingStatusLog", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.FinalSettlementEntity", b =>
                {
                    b.Property<int>("SettlementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByID")
                        .HasColumnType("int");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<decimal>("CleaningCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DeductionRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ElectricityCharges")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PreparedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreparedByID")
                        .HasColumnType("int");

                    b.Property<string>("SettlementStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SettlementID");

                    b.HasIndex("BookingID");

                    b.ToTable("FinalSettlement", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.ImageBannerEntity", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImgId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImgPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ImgId");

                    b.ToTable("ImageBanner", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.OfficeUserEntity", b =>
                {
                    b.Property<int>("OfficeUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeUserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OfficeUserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("OfficeUser", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.OfficeUserRoleEntity", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("OfficeUserRole", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.OtpLogEntity", b =>
                {
                    b.Property<int>("OTPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OTPID"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OTPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OTPID");

                    b.ToTable("OTPLog", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.PaymentTransactionEntity", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionRefNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TransactionID");

                    b.HasIndex("BookingID");

                    b.HasIndex("TransactionRefNo")
                        .IsUnique();

                    b.ToTable("PaymentTransaction", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.RegisteredUserEntity", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("Email IS NOT NULL");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("RegisteredUser", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.SmsLogEntity", b =>
                {
                    b.Property<int>("SMSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SMSID"));

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SMSID");

                    b.ToTable("SMSLog", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.SuperAdminProvisioningTokenEntity", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<byte[]>("BoundIpFingerprint")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("SuperAdminProvisioningToken", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.TermsAndConditionsEntity", b =>
                {
                    b.Property<int>("TermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TermText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TermID");

                    b.ToTable("TermsAndConditions", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.TextAdvertisementEntity", b =>
                {
                    b.Property<int>("TextAdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TextAdID"));

                    b.Property<string>("Advertise")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AdText");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("TextAdID");

                    b.ToTable("TextAdvertisement", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueBlockedDateEntity", b =>
                {
                    b.Property<int>("BlockedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockedID"));

                    b.Property<DateTime>("BlockedDate")
                        .HasColumnType("date");

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("BlockedID");

                    b.HasIndex("BookingID");

                    b.HasIndex("VenueID", "BlockedDate")
                        .IsUnique();

                    b.ToTable("VenueBlockedDate", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueEarningExpenseEntity", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EnteredByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("bit");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("EntryID");

                    b.HasIndex("EnteredByID");

                    b.HasIndex("VenueID");

                    b.ToTable("VenueEarningExpense", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueImageEntity", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("VenueID");

                    b.ToTable("VenueImage", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueMasterEntity", b =>
                {
                    b.Property<int>("VenueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Facilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleMapLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("VenueCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VenueTypeID")
                        .HasColumnType("int");

                    b.HasKey("VenueID");

                    b.HasIndex("VenueTypeID");

                    b.ToTable("VenueMaster", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueRentRuleEntity", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllottable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<string>("NotAllottableReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PurposeID")
                        .HasColumnType("int");

                    b.Property<decimal>("RentPerDay")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SecurityDeposit")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PurposeID");

                    b.HasIndex("VenueID");

                    b.ToTable("VenueRentRule", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueTypeEntity", b =>
                {
                    b.Property<int>("VenueTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueTypeID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VenueTypeID");

                    b.ToTable("VenueType", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueUserMappingEntity", b =>
                {
                    b.Property<int>("MappingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OfficeUserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleLevel")
                        .HasColumnType("int");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("MappingID");

                    b.HasIndex("OfficeUserID");

                    b.HasIndex("RoleLevel");

                    b.HasIndex("VenueID", "OfficeUserID", "RoleLevel")
                        .IsUnique();

                    b.ToTable("VenueUserMapping", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.WebsiteVisitEntity", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VisitID");

                    b.ToTable("WebsiteVisit", (string)null);
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingRequestEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingPurposeEntity", null)
                        .WithMany()
                        .HasForeignKey("PurposeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.RegisteredUserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.BookingStatusLogEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.FinalSettlementEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.OfficeUserEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.OfficeUserRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.PaymentTransactionEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueBlockedDateEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueEarningExpenseEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.OfficeUserEntity", null)
                        .WithMany()
                        .HasForeignKey("EnteredByID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueImageEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueMasterEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueRentRuleEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingCategoryEntity", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.BookingPurposeEntity", null)
                        .WithMany()
                        .HasForeignKey("PurposeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookingSystem.Shared.Models.VenueUserMappingEntity", b =>
                {
                    b.HasOne("OnlineBookingSystem.Shared.Models.OfficeUserEntity", null)
                        .WithMany()
                        .HasForeignKey("OfficeUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.OfficeUserRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleLevel")
                        .IsRequired();

                    b.HasOne("OnlineBookingSystem.Shared.Models.VenueMasterEntity", null)
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
